spring:
  datasource:
    url: jdbc:mysql://localhost:3306/carddb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: card_user
    password: card_password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false

server:
  port: 8080

logging:
  level:
    root: INFO
    com.hyperativa: DEBUG

jwt:
  secret: "CHANGE_THIS_SECRET_IN_PRODUCTION"
  expiration-in-ms: 3600000

card:
  hash-pepper: "CHANGE_THIS_PEPPER_IN_PRODUCTION"
